
try{
    let a=0
    console.log(b)
    console.log("Program succesfully run")
}
catch(error){
    console.log("Error"+error)
}
//Always runs in all cases, no matter what.
finally{
    console.log("Anything is finally always runs even is there is an error")
}
console.log("End")